spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/someone/Documents/idea_projects/blog/dev-application-config
      enabled: true
  profiles:
     active: native
  security:
    user:
      name: configUser
      password: configPassword

server:
  port: 9091

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://discUser:discPassword@localhost:9092/eureka/
#    registry-fetch-interval-seconds: 5
#    region: default



#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false