spring:
  session:
    store-type: none
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: file:/home/someone/Documents/idea_projects/blog/dev-application-config
      enabled: true
  profiles:
     active: native
  security:
    user:
      name: ${BLOG_CONFIG_SERVICE_USERNAME}
      password: ${BLOG_CONFIG_SERVICE_PASSWORD}

server:
  port: 9081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:9082/eureka/


