spring:
  session:
    store-type: none
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          searchPaths:
            - '{application}'
            - shared
      enabled: true
  profiles:
     active: native
  security:
    user:
      name: ${BLOG_CONFIG_SERVICE_USERNAME}
      password: ${BLOG_CONFIG_SERVICE_PASSWORD}

server:
  port: 9081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${BLOG_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}


