#dist: bionic
#sudo: required

services:
  - docker

language: java
jdk: oraclejdk11

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
#  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=amberlight303/blog-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # DISCOVERY
  - export DISCOVERY=amberlight303/blog-discovery
  - docker build -t $DISCOVERY:$COMMIT ./discovery
  - docker tag $DISCOVERY:$COMMIT $DISCOVERY:$TAG
  - docker push $DISCOVERY

  # GATEWAY
  - export GATEWAY=amberlight303/blog-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # POST SERVICE
  - export SVC_POST=amberlight303/blog-svc-post
  - docker build -t $SVC_POST:$COMMIT ./svc-post
  - docker tag $SVC_POST:$COMMIT $SVC_POST:$TAG
  - docker push $SVC_POST

  # MONGO DB
  - export MONGO_DB=amberlight303/blog-mongodb
  - docker build -t $MONGO_DB:$COMMIT ./mongodb
  - docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
  - docker push $MONGO_DB

  # REDIS
  - export REDIS=amberlight303/blog-redis
  - docker build -t $REDIS:$COMMIT ./redis
  - docker tag $REDIS:$COMMIT $REDIS:$TAG
  - docker push $REDIS

  # ELASTICSEARCH
  - export ELASTICSEARCH=amberlight303/blog-elasticsearch
  - docker build -t $ELASTICSEARCH:$COMMIT ./elasticsearch
  - docker tag $ELASTICSEARCH:$COMMIT $ELASTICSEARCH:$TAG
  - docker push $ELASTICSEARCH

  # LOGSTASH
  - export LOGSTASH=amberlight303/blog-logstash
  - docker build -t $LOGSTASH:$COMMIT ./logstash
  - docker tag $LOGSTASH:$COMMIT $LOGSTASH:$TAG
  - docker push $LOGSTASH

  # KIBANA
  - export KIBANA=amberlight303/blog-kibana
  - docker build -t $KIBANA:$COMMIT ./kibana
  - docker tag $KIBANA:$COMMIT $KIBANA:$TAG
  - docker push $KIBANA

  # POSTGRESQL
  - export POSTGRESQL=amberlight303/blog-postgresql
  - docker build -t $POSTGRESQL:$COMMIT ./postgresql
  - docker tag $POSTGRESQL:$COMMIT $POSTGRESQL:$TAG
  - docker push $POSTGRESQL





