version: '3.3'
services:

  config:
    environment:
      BLOG_CONFIG_SERVICE_USERNAME: $BLOG_CONFIG_SERVICE_USERNAME
      BLOG_CONFIG_SERVICE_PASSWORD: $BLOG_CONFIG_SERVICE_PASSWORD
      BLOG_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: $BLOG_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
    image: amberlight303/blog-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery:
    environment:
      BLOG_CONFIG_SERVICE_USERNAME: $BLOG_CONFIG_SERVICE_USERNAME
      BLOG_CONFIG_SERVICE_PASSWORD: $BLOG_CONFIG_SERVICE_PASSWORD
      BLOG_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: $BLOG_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
      BLOG_REDIS_HOST: $BLOG_REDIS_HOST
      BLOG_REDIS_PORT: $BLOG_REDIS_PORT
      BLOG_REDIS_PASSWORD: $BLOG_REDIS_PASSWORD
      BLOG_SPRING_CLOUD_CONFIG_URI: $BLOG_SPRING_CLOUD_CONFIG_URI
    image: amberlight303/blog-discovery
    restart: always
#    depends_on:
#      config:
#        condition: service_healthy
    ports:
      - "127.0.0.1:9082:9082"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      BLOG_CONFIG_SERVICE_USERNAME: $BLOG_CONFIG_SERVICE_USERNAME
      BLOG_CONFIG_SERVICE_PASSWORD: $BLOG_CONFIG_SERVICE_PASSWORD
      BLOG_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: $BLOG_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
      BLOG_MONGODB_HOST: $BLOG_MONGODB_HOST
      BLOG_MONGODB_PORT: $BLOG_MONGODB_PORT
      BLOG_MONGODB_AUTHENTICATION_DATABASE: $BLOG_MONGODB_AUTHENTICATION_DATABASE
      BLOG_MONGODB_DATABASE: $BLOG_MONGODB_DATABASE
      BLOG_MONGODB_USERNAME: $BLOG_MONGODB_USERNAME
      BLOG_MONGODB_PASSWORD: $BLOG_MONGODB_PASSWORD
      BLOG_POSTGRESQL_URL: $BLOG_POSTGRESQL_URL
      BLOG_POSTGRESQL_USERNAME: $BLOG_POSTGRESQL_USERNAME
      BLOG_POSTGRESQL_PASSWORD: $BLOG_POSTGRESQL_PASSWORD
      BLOG_REDIS_HOST: $BLOG_REDIS_HOST
      BLOG_REDIS_PORT: $BLOG_REDIS_PORT
      BLOG_REDIS_PASSWORD: $BLOG_REDIS_PASSWORD
      BLOG_SUPPORT_MAIL: $BLOG_SUPPORT_MAIL
      BLOG_SUPPORT_MAIL_PASSWORD: $BLOG_SUPPORT_MAIL_PASSWORD
      BLOG_KAFKA_BOOTSTRAP_ADDRESS: $BLOG_KAFKA_BOOTSTRAP_ADDRESS
      BLOG_ELASTICSEARCH_HOST: $BLOG_ELASTICSEARCH_HOST
      BLOG_ELASTICSEARCH_PORT: $BLOG_ELASTICSEARCH_PORT
      BLOG_ELASTICSEARCH_CLUSTER_NAME: $BLOG_ELASTICSEARCH_CLUSTER_NAME
      BLOG_ELASTICSEARCH_CLUSTER_NODES: $BLOG_ELASTICSEARCH_CLUSTER_NODES
      BLOG_SPRING_CLOUD_CONFIG_URI: $BLOG_SPRING_CLOUD_CONFIG_URI
      BLOG_GOOGLE_RECAPTCHA_KEY_SITE: $BLOG_GOOGLE_RECAPTCHA_KEY_SITE
      BLOG_GOOGLE_RECAPTCHA_KEY_SECRET: $BLOG_GOOGLE_RECAPTCHA_KEY_SECRET
      BLOG_REMEMBER_ME_SERVICE_KEY: $BLOG_REMEMBER_ME_SERVICE_KEY
    image: amberlight303/blog-gateway
    restart: always
#    depends_on:
#      config:
#        condition: service_healthy
    ports:
      - "127.0.0.1:9080:9080"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  svc-post:
    environment:
      BLOG_CONFIG_SERVICE_USERNAME: $BLOG_CONFIG_SERVICE_USERNAME
      BLOG_CONFIG_SERVICE_PASSWORD: $BLOG_CONFIG_SERVICE_PASSWORD
      BLOG_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: $BLOG_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
      BLOG_MONGODB_HOST: $BLOG_MONGODB_HOST
      BLOG_MONGODB_PORT: $BLOG_MONGODB_PORT
      BLOG_MONGODB_AUTHENTICATION_DATABASE: $BLOG_MONGODB_AUTHENTICATION_DATABASE
      BLOG_MONGODB_DATABASE: $BLOG_MONGODB_DATABASE
      BLOG_MONGODB_USERNAME: $BLOG_MONGODB_USERNAME
      BLOG_MONGODB_PASSWORD: $BLOG_MONGODB_PASSWORD
      BLOG_POSTGRESQL_URL: $BLOG_POSTGRESQL_URL
      BLOG_POSTGRESQL_USERNAME: $BLOG_POSTGRESQL_USERNAME
      BLOG_POSTGRESQL_PASSWORD: $BLOG_POSTGRESQL_PASSWORD
      BLOG_REDIS_HOST: $BLOG_REDIS_HOST
      BLOG_REDIS_PORT: $BLOG_REDIS_PORT
      BLOG_REDIS_PASSWORD: $BLOG_REDIS_PASSWORD
      BLOG_SUPPORT_MAIL: $BLOG_SUPPORT_MAIL
      BLOG_SUPPORT_MAIL_PASSWORD: $BLOG_SUPPORT_MAIL_PASSWORD
      BLOG_KAFKA_BOOTSTRAP_ADDRESS: $BLOG_KAFKA_BOOTSTRAP_ADDRESS
      BLOG_ELASTICSEARCH_HOST: $BLOG_ELASTICSEARCH_HOST
      BLOG_ELASTICSEARCH_PORT: $BLOG_ELASTICSEARCH_PORT
      BLOG_ELASTICSEARCH_CLUSTER_NAME: $BLOG_ELASTICSEARCH_CLUSTER_NAME
      BLOG_ELASTICSEARCH_CLUSTER_NODES: $BLOG_ELASTICSEARCH_CLUSTER_NODES
      BLOG_SPRING_CLOUD_CONFIG_URI: $BLOG_SPRING_CLOUD_CONFIG_URI
    image: amberlight303/blog-svc-post
    restart: always
#    depends_on:
#      config:
#        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
