# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:7.11.1
MAINTAINER Oleg Vostokov <amberlight303@gmail.com>

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

EXPOSE 5601