# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:7.11.1
MAINTAINER Oleg Vostokov <amberlight303@gmail.com>

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

EXPOSE 9200