# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:7.11.1
MAINTAINER Oleg Vostokov <amberlight303@gmail.com>

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

EXPOSE 9600